import { Geist, Geist_Mono } from "next/font/google";
import { loadEnvConfig } from '@next/env';
import Link from 'next/link';
import "./globals.css";
import Navbar from '@/app/components/navbar';
import AuthTheme from "./providers/authProvider";

const projectDir = process.cwd()
loadEnvConfig(projectDir);

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthTheme>
          <header>
            <Navbar />
          </header>

          {children}
          
          <footer className="bg-gray-900">
            <div className="max-w-screen-xl px-4 pt-16 pb-6 mx-auto sm:px-6 lg:px-8 lg:pt-24">
              <div className="pt-6 mt-12 border-t border-gray-800">
                <div className="text-center sm:flex sm:justify-between sm:text-left">
                  <p className="text-sm text-gray-400">
                    <a
                      className="inline-block text-teal-500 underline transition hover:text-teal-500/75"
                      href="/"
                    >
                      Terms & Conditions
                    </a>

                    <span>&middot;</span>

                    <a
                      className="inline-block text-teal-500 underline transition hover:text-teal-500/75"
                      href="/"
                    >
                      Privacy Policy
                    </a>
                  </p>

                  <p className="mt-4 text-sm text-gray-500 sm:order-first sm:mt-0">
                    &copy; 2022 Company Name
                  </p>
                </div>
              </div>
            </div>
          </footer>
        </AuthTheme>
      </body>
    </html>
  );
}